https://stackoverflow.com/questions/16579407/are-there-any-example-data-sets-for-python

In [1]:
from sklearn import datasets

In [9]:
reg = datasets.make_regression()

In [11]:
reg

(array([[-0.47358126, -0.26651055, -1.3611809 , ...,  1.52861177,
         -0.11710135,  0.44857037],
        [ 0.47706562, -0.88094827,  0.90172841, ...,  0.17831321,
         -1.86944792,  0.23793158],
        [-0.83247437, -1.13446944,  0.49726192, ...,  1.01338569,
         -1.30913713,  2.43688885],
        ...,
        [ 0.54220802, -0.28629862,  0.45767275, ...,  0.59583737,
          0.60760661, -0.1258195 ],
        [-1.05779111, -0.22773679,  0.36219151, ...,  0.19139785,
          0.55939824,  0.52991986],
        [ 1.00086009,  1.52293774,  0.24624573, ..., -0.03633606,
         -0.38360445, -0.61866233]]),
 array([ -82.44160104, -191.65615628,   20.595872  ,   64.16368753,
         -77.19322346,   19.11179762,  -24.41478452,   98.62255871,
         -16.41086945,   -3.05588244,   53.92834488,   88.6520145 ,
          45.61196881,  -27.70541876,  129.36752634,  -45.26599553,
         -61.70707046,  -26.57041238,   77.23785466,   47.31934271,
         -59.11227199,   16.76750

In [6]:
iris = datasets.load_iris()

In [8]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [13]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [14]:
X = iris.data

In [15]:
y = iris.target

In [24]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [25]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [26]:
y = to_categorical(y)

In [29]:
?to_categorical

In [31]:
y[0:10]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [32]:
from keras.preprocessing.text import Tokenizer

In [33]:
sentences = [
    "I love my dog",
    "I, love my cat"
]

In [36]:
tokenizer = Tokenizer(num_words = 100)
tokenizer.fit_on_texts(sentences)

In [38]:
word_index = tokenizer.word_index
print(word_index)

{'i': 1, 'love': 2, 'my': 3, 'dog': 4, 'cat': 5}


In [53]:
tokenizer.word_counts

OrderedDict([('i', 2), ('love', 2), ('my', 2), ('dog', 1), ('cat', 1)])

In [41]:
import pandas as pd

In [56]:
orderedDictList = tokenizer.word_counts

In [58]:
df = pd.DataFrame(orderedDictList, index = [0])

In [59]:
df

i  love  my  dog  cat
0  2     2   2    1    1

In [55]:
pd.DataFrame.from_dict(tokenizer.word_counts,columns=tokenizer.word_counts.keys())

ValueError: cannot use columns parameter with orient='columns'

In [1]:
import pandas as pd

In [3]:
strings = ["iron man", "the incredible hulk", "iron man 2", 
           "thor", "captain america: the first avenger",
           "marvel's the avengers", "iron man 3", 
           "thor: the dark world","captain america: the winter soldier", 
           "guardians of the galaxy"]

In [5]:
strings_df = pd.DataFrame({"movies":strings})
strings_df

movies
0                             iron man
1                  the incredible hulk
2                           iron man 2
3                                 thor
4   captain america: the first avenger
5                marvel's the avengers
6                           iron man 3
7                 thor: the dark world
8  captain america: the winter soldier
9              guardians of the galaxy

In [13]:
strings_df.movies[strings_df.movies.str.contains("captain")]

4     captain america: the first avenger
8    captain america: the winter soldier
Name: movies, dtype: object

In [11]:
strings_df.movies.str.contains("captain")

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
9    False
Name: movies, dtype: bool

In [15]:
strings_df

movies
0                             iron man
1                  the incredible hulk
2                           iron man 2
3                                 thor
4   captain america: the first avenger
5                marvel's the avengers
6                           iron man 3
7                 thor: the dark world
8  captain america: the winter soldier
9              guardians of the galaxy

In [16]:
strings_df.query('strings_df.movies.str.contains("captain")')

UndefinedVariableError: name 'strings_df' is not defined

# Questions: How to colour the backgroud of Text in Jupyter Notebook

In [3]:
# Copy Below code and make that Cell as Markdown

## <span style='background :pink' > Background color is yellow </span>

## <span style='background :pink' > Background color is yellow </span>

In [ ]:
#79BAEC

## <span style='background :#C2DFFF' > Background color is yellow </span>

https://www.computerhope.com/htmcolor.htm

# Question: How the change the backgroud colour of Jupyter Notebook Cell

Links: 
 - https://medium.com/analytics-vidhya/the-ultimate-markdown-guide-for-jupyter-notebook-d5e5abf728fd
 - https://www.ibm.com/support/knowledgecenter/en/SSGNPV_2.0.0/dsx/markd-jupyter.html

<div class="alert alert-block alert-info">
    <b><large>Creating Scenario</large></b>  
</div>

<div class="alert alert-block alert-info">
    <b>Tip: Use blue boxes (alert-info) for tips and notes.</b>  
</div>

<div class="alert alert-block alert-info">
<b>Tip:</b> Use blue boxes (alert-info) for tips and notes.</div>

<div class="alert alert-block alert-warning">
<b>Example:</b> Use yellow boxes for examples that are not inside code cells, or use for mathematical formulas if needed. Typically also used to display warning messages.
</div>

<div class="alert alert-block alert-success">
<b>Success:</b> This alert box indicates a successful or positive action.
</div>

<div class="alert alert-block alert-danger">
<b>Danger:</b> This alert box indicates a dangerous or potentially negative action.
</div>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import r2_score, confusion_matrix, classification_report