## Installation

 - Open Anaconda Prompt
 - Type the below command and run 
    - `conda install -c anaconda py-xgboost`
 - [xgboost Documentation](https://xgboost.readthedocs.io/en/latest/python/python_intro.html)

In [101]:
import numpy as np
import pandas as pd

In [102]:
import xgboost as xgb

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
#pwd

In [105]:
iris = pd.read_csv("iris.csv")
#iris = pd.read_csv("https://bit.ly/ds-iris")

In [106]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [107]:
X = iris.iloc[:,:-1]
y = iris.iloc[:,-1]

In [108]:
X_train, X_test, y_train, y_test= train_test_split(X, y,test_size=0.2, random_state=123)

In [109]:
type(X_train)

pandas.core.frame.DataFrame

In [110]:
xg_cl = xgb.XGBClassifier(objective='binary:logistic', seed=123)

In [111]:
xg_cl.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=123,
       silent=True, subsample=1)

In [112]:
xg_cl.score(X_train,y_train)

C:\Users\mohammads6\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


1.0

In [113]:
xg_cl.score(X_test,y_test)

C:\Users\mohammads6\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


0.9666666666666667

In [114]:
xg_cl.feature_importances_

array([0.1362963 , 0.09777778, 0.41777778, 0.34814814], dtype=float32)

In [115]:
from sklearn.ensemble import RandomForestClassifier
rf_c = RandomForestClassifier()
rf_c.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [116]:
rf_c.score(X_train,y_train)

0.9916666666666667

In [117]:
rf_c.score(X_test,y_test)

0.9333333333333333

## XGBOOST

In [118]:
xg_reg = xgb.XGBRegressor(objective='reg:linear', seed=123) #,n_estimators=10

In [119]:
mtcars = pd.read_csv("mtcars.csv")

In [120]:
# mtcars = pd.read_csv("https://bit.ly/ds-mtcars")

In [121]:
mtcars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
mpg     32 non-null float64
cyl     32 non-null int64
disp    32 non-null float64
hp      32 non-null int64
drat    32 non-null float64
wt      32 non-null float64
qsec    32 non-null float64
vs      32 non-null int64
am      32 non-null int64
gear    32 non-null int64
carb    32 non-null int64
cars    32 non-null object
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [122]:
X = mtcars.drop(["cars", "mpg"], axis=1)
y = mtcars.mpg

In [123]:
X.head()

cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [124]:
y.head()

0    21.0
1    21.0
2    22.8
3    21.4
4    18.7
Name: mpg, dtype: float64

In [125]:
X_train, X_test, y_train, y_test= train_test_split(X, y,test_size=0.2, random_state=123)

In [126]:
type(X_train)

pandas.core.frame.DataFrame

In [127]:
from sklearn.preprocessing import StandardScaler

In [82]:
ss = StandardScaler()

In [128]:
#Standardize the data
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [129]:
# X_train.head()

In [130]:
xg_reg.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=123,
       silent=True, subsample=1)

In [132]:
xg_reg.feature_importances_

array([0.02233251, 0.35235733, 0.15136476, 0.08436725, 0.16377172,
       0.17617866, 0.        , 0.00248139, 0.01240695, 0.03473945],
      dtype=float32)

In [144]:
# =============================================================================
# Feature Importance
# =============================================================================
feature_values = xg_reg.feature_importances_
feature_names = X.columns


feature_imporantance = pd.DataFrame({"feature_names":feature_names,
                                     "feature_values":feature_values}).sort_values("feature_values", ascending=False)
feature_imporantance 

feature_names  feature_values
1          disp        0.352357
5          qsec        0.176179
4            wt        0.163772
2            hp        0.151365
3          drat        0.084367
9          carb        0.034739
0           cyl        0.022333
8          gear        0.012407
7            am        0.002481
6            vs        0.000000

In [145]:
preds = xg_reg.predict(X_test)

In [146]:
preds

array([21.267101, 21.656443, 18.631794, 21.713152, 21.267101, 22.715368,
       15.541982], dtype=float32)

In [147]:
y_test

7     24.4
31    21.4
5     18.1
26    26.0
8     22.8
27    30.4
12    17.3
Name: mpg, dtype: float64

In [148]:
xg_reg.score(X_train,y_train)

0.9994126763748031

In [149]:
xg_reg.score(X_test,y_test)

0.2543421879046974

In [150]:
from sklearn.ensemble import RandomForestRegressor

In [139]:
rf = RandomForestRegressor()

In [140]:
rf.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [141]:
rf.score(X_train,y_train)

0.9757884152112192

In [142]:
rf.score(X_test,y_test)

0.530718358560993